# This file generates the GitHub Actions matrix
---
include:
  - board: nice_nano_v2
    shield: typhon_left
    # the following are for enabling ZMK Studio https://v0-3-branch.zmk.dev/docs/features/studio#keymap-changes
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y
  - board: nice_nano_v2
    shield: caldera_right
  - board: nice_nano_v2
    shield: settings_reset